# Generated by Django 2.2.4 on 2019-08-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quiz.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='quiz.User')),
            ],
        ),
    ]
