# Generated by Django 2.2.4 on 2019-08-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190810_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='result',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='quiz.Question'),
        ),
    ]
